# conda env create -f /home/cspeakes/PycharmProjects/speak-query/environment.yml
name: speakQueryEnv
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - aiosqlite
  - antlr4-python3-runtime
  - defusedxml
  - apscheduler>=3,<4
  - croniter
  - flask
  - flask-wtf
  - pandas
  - pyarrow
  - pyparsing
  - pyyaml
  - requests
  - aiosmtplib
  - restrictedpython
  - jpype1
  - faker
prefix: /home/cspeakes/anaconda3/envs/speakQueryEnv
