[package]
name = "r_index_call"
version = "0.1.0"
edition = "2021"

[lib]
name = "r_index_call"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
glob = "0.3"
regex = "1"
